"""user states

Revision ID: 1af56ef5ac3c
Revises: f02f9e75f973
Create Date: 2020-08-28 12:38:34.134130

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "1af56ef5ac3c"
down_revision = "f02f9e75f973"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user",
        sa.Column(
            "state",
            sa.Enum("REGISTERED", "ACTIVE", "BLOCKED", name="userstate"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "state")
    # ### end Alembic commands ###
