"""Adding table that keeps track of open source products.

Revision ID: 32ded3390554
Revises: 82f8f48c6ee6
Create Date: 2019-06-16 12:13:28.964876

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "32ded3390554"
down_revision = "82f8f48c6ee6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "oss_products",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("date_created", sa.DateTime(), nullable=True),
        sa.Column("date_modified", sa.DateTime(), nullable=True),
        sa.Column("vendor", sa.String(length=255), nullable=False),
        sa.Column("product", sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("vendor", "product"),
    )
    op.create_index(
        "idx_oss_products_main", "oss_products", ["vendor", "product"], unique=True
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_oss_products_main", table_name="oss_products")
    op.drop_table("oss_products")
    # ### end Alembic commands ###
