"""Initial layout

Revision ID: 82f8f48c6ee6
Revises: 
Create Date: 2019-05-02 21:01:25.700648

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "82f8f48c6ee6"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "affects",
        sa.Column("id", mysql.INTEGER(display_width=10), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(), nullable=True),
        sa.Column("updated_at", sa.TIMESTAMP(), nullable=True),
        sa.Column("deleted_at", sa.TIMESTAMP(), nullable=True),
        sa.Column("nvd_json_id", mysql.INTEGER(display_width=10), nullable=True),
        sa.Column("vendor", sa.String(length=255), nullable=True),
        sa.Column("product", sa.String(length=255), nullable=True),
        sa.Column("version", sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        schema="cve",
    )
    op.create_index(
        "idx_affects_deleted_at", "affects", ["deleted_at"], unique=False, schema="cve"
    )
    op.create_index(
        "idx_affects_nvd_json_id",
        "affects",
        ["nvd_json_id"],
        unique=False,
        schema="cve",
    )
    op.create_table(
        "cve_details",
        sa.Column("id", mysql.INTEGER(display_width=10), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(), nullable=True),
        sa.Column("updated_at", sa.TIMESTAMP(), nullable=True),
        sa.Column("deleted_at", sa.TIMESTAMP(), nullable=True),
        sa.Column("cve_id", sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        schema="cve",
    )
    op.create_index(
        "idx_cve_detail_cveid", "cve_details", ["cve_id"], unique=False, schema="cve"
    )
    op.create_index(
        "idx_cve_details_deleted_at",
        "cve_details",
        ["deleted_at"],
        unique=False,
        schema="cve",
    )
    op.create_table(
        "cvss2",
        sa.Column("id", mysql.INTEGER(display_width=10), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(), nullable=True),
        sa.Column("updated_at", sa.TIMESTAMP(), nullable=True),
        sa.Column("deleted_at", sa.TIMESTAMP(), nullable=True),
        sa.Column("jvn_id", mysql.INTEGER(display_width=10), nullable=True),
        sa.Column("vector_string", sa.String(length=255), nullable=True),
        sa.Column("access_vector", sa.String(length=255), nullable=True),
        sa.Column("access_complexity", sa.String(length=255), nullable=True),
        sa.Column("authentication", sa.String(length=255), nullable=True),
        sa.Column("confidentiality_impact", sa.String(length=255), nullable=True),
        sa.Column("integrity_impact", sa.String(length=255), nullable=True),
        sa.Column("availability_impact", sa.String(length=255), nullable=True),
        sa.Column("base_score", sa.Float(asdecimal=True), nullable=True),
        sa.Column("severity", sa.String(length=255), nullable=True),
        sa.Column("nvd_xml_id", mysql.INTEGER(display_width=10), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        schema="cve",
    )
    op.create_index(
        "idx_cvss2_deleted_at", "cvss2", ["deleted_at"], unique=False, schema="cve"
    )
    op.create_index("idx_cvss2_jvn_id", "cvss2", ["jvn_id"], unique=False, schema="cve")
    op.create_index(
        "idx_cvsss2_nvd_xml_id", "cvss2", ["nvd_xml_id"], unique=False, schema="cve"
    )
    op.create_table(
        "cvss2_extras",
        sa.Column("id", mysql.INTEGER(display_width=10), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(), nullable=True),
        sa.Column("updated_at", sa.TIMESTAMP(), nullable=True),
        sa.Column("deleted_at", sa.TIMESTAMP(), nullable=True),
        sa.Column("nvd_xml_id", mysql.INTEGER(display_width=10), nullable=True),
        sa.Column("jvn_id", mysql.INTEGER(display_width=10), nullable=True),
        sa.Column("vector_string", sa.String(length=255), nullable=True),
        sa.Column("access_vector", sa.String(length=255), nullable=True),
        sa.Column("access_complexity", sa.String(length=255), nullable=True),
        sa.Column("authentication", sa.String(length=255), nullable=True),
        sa.Column("confidentiality_impact", sa.String(length=255), nullable=True),
        sa.Column("integrity_impact", sa.String(length=255), nullable=True),
        sa.Column("availability_impact", sa.String(length=255), nullable=True),
        sa.Column("base_score", sa.Float(asdecimal=True), nullable=True),
        sa.Column("severity", sa.String(length=255), nullable=True),
        sa.Column("exploitability_score", sa.Float(asdecimal=True), nullable=True),
        sa.Column("impact_score", sa.Float(asdecimal=True), nullable=True),
        sa.Column(
            "obtain_all_privilege", mysql.TINYINT(display_width=1), nullable=True
        ),
        sa.Column(
            "obtain_user_privilege", mysql.TINYINT(display_width=1), nullable=True
        ),
        sa.Column(
            "obtain_other_privilege", mysql.TINYINT(display_width=1), nullable=True
        ),
        sa.Column(
            "user_interaction_required", mysql.TINYINT(display_width=1), nullable=True
        ),
        sa.Column("nvd_json_id", mysql.INTEGER(display_width=10), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        schema="cve",
    )
    op.create_index(
        "idx_cvss2_extras_deleted_at",
        "cvss2_extras",
        ["deleted_at"],
        unique=False,
        schema="cve",
    )
    op.create_index(
        "idx_cvsss2_extra_nvd_json_id",
        "cvss2_extras",
        ["nvd_json_id"],
        unique=False,
        schema="cve",
    )
    op.create_table(
        "env_cpes",
        sa.Column("id", mysql.INTEGER(display_width=10), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(), nullable=True),
        sa.Column("updated_at", sa.TIMESTAMP(), nullable=True),
        sa.Column("deleted_at", sa.TIMESTAMP(), nullable=True),
        sa.Column("well_formed_name", sa.Text(), nullable=True),
        sa.Column("part", sa.String(length=255), nullable=True),
        sa.Column("vendor", sa.String(length=255), nullable=True),
        sa.Column("product", sa.String(length=255), nullable=True),
        sa.Column("version", sa.String(length=255), nullable=True),
        sa.Column("update", sa.String(length=255), nullable=True),
        sa.Column("edition", sa.String(length=255), nullable=True),
        sa.Column("language", sa.String(length=255), nullable=True),
        sa.Column("software_edition", sa.String(length=255), nullable=True),
        sa.Column("target_sw", sa.String(length=255), nullable=True),
        sa.Column("target_hw", sa.String(length=255), nullable=True),
        sa.Column("other", sa.String(length=255), nullable=True),
        sa.Column("version_start_excluding", sa.String(length=255), nullable=True),
        sa.Column("version_start_including", sa.String(length=255), nullable=True),
        sa.Column("version_end_excluding", sa.String(length=255), nullable=True),
        sa.Column("version_end_including", sa.String(length=255), nullable=True),
        sa.Column("cpe_id", mysql.INTEGER(display_width=10), nullable=True),
        sa.Column("uri", sa.String(length=255), nullable=True),
        sa.Column("formatted_string", sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        schema="cve",
    )
    op.create_index(
        "idx_env_cpes_deleted_at",
        "env_cpes",
        ["deleted_at"],
        unique=False,
        schema="cve",
    )
    op.create_index(
        "idx_envcpes_cpe_id", "env_cpes", ["cpe_id"], unique=False, schema="cve"
    )
    op.create_index(
        "idx_envcpes_formatted_string",
        "env_cpes",
        ["formatted_string"],
        unique=False,
        schema="cve",
    )
    op.create_index("idx_envcpes_uri", "env_cpes", ["uri"], unique=False, schema="cve")
    op.create_table(
        "feed_meta",
        sa.Column("id", mysql.INTEGER(display_width=10), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(), nullable=True),
        sa.Column("updated_at", sa.TIMESTAMP(), nullable=True),
        sa.Column("deleted_at", sa.TIMESTAMP(), nullable=True),
        sa.Column("url", sa.String(length=255), nullable=True),
        sa.Column("hash", sa.String(length=255), nullable=True),
        sa.Column("last_modified_date", sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        schema="cve",
    )
    op.create_index(
        "idx_feed_meta_deleted_at",
        "feed_meta",
        ["deleted_at"],
        unique=False,
        schema="cve",
    )
    op.create_table(
        "jvns",
        sa.Column("id", mysql.INTEGER(display_width=10), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(), nullable=True),
        sa.Column("updated_at", sa.TIMESTAMP(), nullable=True),
        sa.Column("deleted_at", sa.TIMESTAMP(), nullable=True),
        sa.Column("cve_detail_id", mysql.INTEGER(display_width=10), nullable=True),
        sa.Column("title", sa.String(length=255), nullable=True),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("jvn_link", sa.String(length=255), nullable=True),
        sa.Column("jvn_id", sa.String(length=255), nullable=True),
        sa.Column("published_date", sa.TIMESTAMP(), nullable=True),
        sa.Column("last_modified_date", sa.TIMESTAMP(), nullable=True),
        sa.Column("cve_id", sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        schema="cve",
    )
    op.create_index(
        "idx_jvns_cve_detail_id", "jvns", ["cve_detail_id"], unique=False, schema="cve"
    )
    op.create_index("idx_jvns_cveid", "jvns", ["cve_id"], unique=False, schema="cve")
    op.create_index(
        "idx_jvns_deleted_at", "jvns", ["deleted_at"], unique=False, schema="cve"
    )
    op.create_table(
        "nvd_jsons",
        sa.Column("id", mysql.INTEGER(display_width=10), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(), nullable=True),
        sa.Column("updated_at", sa.TIMESTAMP(), nullable=True),
        sa.Column("deleted_at", sa.TIMESTAMP(), nullable=True),
        sa.Column("cve_detail_id", mysql.INTEGER(display_width=10), nullable=True),
        sa.Column("published_date", sa.TIMESTAMP(), nullable=True),
        sa.Column("last_modified_date", sa.TIMESTAMP(), nullable=True),
        sa.Column("cve_id", sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        schema="cve",
    )
    op.create_index(
        "idx_nvd_jsons_cve_detail_id",
        "nvd_jsons",
        ["cve_detail_id"],
        unique=False,
        schema="cve",
    )
    op.create_index(
        "idx_nvd_jsons_cveid", "nvd_jsons", ["cve_id"], unique=False, schema="cve"
    )
    op.create_index(
        "idx_nvd_jsons_deleted_at",
        "nvd_jsons",
        ["deleted_at"],
        unique=False,
        schema="cve",
    )
    op.create_table(
        "nvd_xmls",
        sa.Column("id", mysql.INTEGER(display_width=10), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(), nullable=True),
        sa.Column("updated_at", sa.TIMESTAMP(), nullable=True),
        sa.Column("deleted_at", sa.TIMESTAMP(), nullable=True),
        sa.Column("cve_detail_id", mysql.INTEGER(display_width=10), nullable=True),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("published_date", sa.TIMESTAMP(), nullable=True),
        sa.Column("last_modified_date", sa.TIMESTAMP(), nullable=True),
        sa.Column("cve_id", sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        schema="cve",
    )
    op.create_index(
        "idx_nvd_xmls_cve_detail_id",
        "nvd_xmls",
        ["cve_detail_id"],
        unique=False,
        schema="cve",
    )
    op.create_index(
        "idx_nvd_xmls_cveid", "nvd_xmls", ["cve_id"], unique=False, schema="cve"
    )
    op.create_index(
        "idx_nvd_xmls_deleted_at",
        "nvd_xmls",
        ["deleted_at"],
        unique=False,
        schema="cve",
    )
    op.create_table(
        "cwe_data",
        sa.Column("cwe_id", sa.String(length=255), nullable=False),
        sa.Column("cwe_name", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("cwe_id"),
        schema="cwe",
    )
    op.create_index(
        op.f("ix_cwe_cwe_data_cwe_id"),
        "cwe_data",
        ["cwe_id"],
        unique=False,
        schema="cwe",
    )
    op.create_table(
        "user",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("date_created", sa.DateTime(), nullable=True),
        sa.Column("date_modified", sa.DateTime(), nullable=True),
        sa.Column("email", sa.String(length=256), nullable=True),
        sa.Column("full_name", sa.String(length=256), nullable=True),
        sa.Column("profile_picture", sa.String(length=256), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "cpes",
        sa.Column("id", mysql.INTEGER(display_width=10), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(), nullable=True),
        sa.Column("updated_at", sa.TIMESTAMP(), nullable=True),
        sa.Column("deleted_at", sa.TIMESTAMP(), nullable=True),
        sa.Column("jvn_id", mysql.INTEGER(display_width=10), nullable=True),
        sa.Column("nvd_xml_id", mysql.INTEGER(display_width=10), nullable=True),
        sa.Column("uri", sa.String(length=255), nullable=True),
        sa.Column("formatted_string", sa.String(length=255), nullable=True),
        sa.Column("well_formed_name", sa.Text(), nullable=True),
        sa.Column("part", sa.String(length=255), nullable=True),
        sa.Column("vendor", sa.String(length=255), nullable=True),
        sa.Column("product", sa.String(length=255), nullable=True),
        sa.Column("version", sa.String(length=255), nullable=True),
        sa.Column("update", sa.String(length=255), nullable=True),
        sa.Column("edition", sa.String(length=255), nullable=True),
        sa.Column("language", sa.String(length=255), nullable=True),
        sa.Column("software_edition", sa.String(length=255), nullable=True),
        sa.Column("target_sw", sa.String(length=255), nullable=True),
        sa.Column("target_hw", sa.String(length=255), nullable=True),
        sa.Column("other", sa.String(length=255), nullable=True),
        sa.Column("version_start_excluding", sa.String(length=255), nullable=True),
        sa.Column("version_start_including", sa.String(length=255), nullable=True),
        sa.Column("version_end_excluding", sa.String(length=255), nullable=True),
        sa.Column("version_end_including", sa.String(length=255), nullable=True),
        sa.Column("nvd_json_id", mysql.INTEGER(display_width=10), nullable=True),
        sa.ForeignKeyConstraint(
            ["nvd_json_id"],
            ["cve.nvd_jsons.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="cve",
    )
    op.create_index(
        "idx_cpes_deleted_at", "cpes", ["deleted_at"], unique=False, schema="cve"
    )
    op.create_index(
        "idx_cpes_formatted_string",
        "cpes",
        ["formatted_string"],
        unique=False,
        schema="cve",
    )
    op.create_index("idx_cpes_jvn_id", "cpes", ["jvn_id"], unique=False, schema="cve")
    op.create_index(
        "idx_cpes_nvd_json_id", "cpes", ["nvd_json_id"], unique=False, schema="cve"
    )
    op.create_index(
        "idx_cpes_nvd_xml_id", "cpes", ["nvd_xml_id"], unique=False, schema="cve"
    )
    op.create_index("idx_cpes_part", "cpes", ["part"], unique=False, schema="cve")
    op.create_index("idx_cpes_product", "cpes", ["product"], unique=False, schema="cve")
    op.create_index("idx_cpes_uri", "cpes", ["uri"], unique=False, schema="cve")
    op.create_index("idx_cpes_vendor", "cpes", ["vendor"], unique=False, schema="cve")
    op.create_table(
        "cvss3",
        sa.Column("id", mysql.INTEGER(display_width=10), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(), nullable=True),
        sa.Column("updated_at", sa.TIMESTAMP(), nullable=True),
        sa.Column("deleted_at", sa.TIMESTAMP(), nullable=True),
        sa.Column("jvn_id", mysql.INTEGER(display_width=10), nullable=True),
        sa.Column("vector_string", sa.String(length=255), nullable=True),
        sa.Column("attack_vector", sa.String(length=255), nullable=True),
        sa.Column("attack_complexity", sa.String(length=255), nullable=True),
        sa.Column("privileges_required", sa.String(length=255), nullable=True),
        sa.Column("user_interaction", sa.String(length=255), nullable=True),
        sa.Column("scope", sa.String(length=255), nullable=True),
        sa.Column("confidentiality_impact", sa.String(length=255), nullable=True),
        sa.Column("integrity_impact", sa.String(length=255), nullable=True),
        sa.Column("availability_impact", sa.String(length=255), nullable=True),
        sa.Column("base_score", sa.Float(asdecimal=True), nullable=True),
        sa.Column("base_severity", sa.String(length=255), nullable=True),
        sa.Column("exploitability_score", sa.Float(asdecimal=True), nullable=True),
        sa.Column("impact_score", sa.Float(asdecimal=True), nullable=True),
        sa.Column("nvd_json_id", mysql.INTEGER(display_width=10), nullable=True),
        sa.ForeignKeyConstraint(
            ["nvd_json_id"],
            ["cve.nvd_jsons.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="cve",
    )
    op.create_index(
        "idx_cvss3_deleted_at", "cvss3", ["deleted_at"], unique=False, schema="cve"
    )
    op.create_index("idx_cvss3_jvn_id", "cvss3", ["jvn_id"], unique=False, schema="cve")
    op.create_index(
        "idx_cvss3_nvd_json_id", "cvss3", ["nvd_json_id"], unique=False, schema="cve"
    )
    op.create_table(
        "cwes",
        sa.Column("id", mysql.INTEGER(display_width=10), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(), nullable=True),
        sa.Column("updated_at", sa.TIMESTAMP(), nullable=True),
        sa.Column("deleted_at", sa.TIMESTAMP(), nullable=True),
        sa.Column("nvd_xml_id", mysql.INTEGER(display_width=10), nullable=True),
        sa.Column("jvn_id", mysql.INTEGER(display_width=10), nullable=True),
        sa.Column("cwe_id", sa.String(length=255), nullable=True),
        sa.Column("nvd_json_id", mysql.INTEGER(display_width=10), nullable=True),
        sa.ForeignKeyConstraint(
            ["nvd_json_id"],
            ["cve.nvd_jsons.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="cve",
    )
    op.create_index(
        "idx_cwes_deleted_at", "cwes", ["deleted_at"], unique=False, schema="cve"
    )
    op.create_index("idx_cwes_jvn_id", "cwes", ["jvn_id"], unique=False, schema="cve")
    op.create_index(
        "idx_cwes_nvd_json_id", "cwes", ["nvd_json_id"], unique=False, schema="cve"
    )
    op.create_index(
        "idx_cwes_nvd_xml_id", "cwes", ["nvd_xml_id"], unique=False, schema="cve"
    )
    op.create_table(
        "descriptions",
        sa.Column("id", mysql.INTEGER(display_width=10), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(), nullable=True),
        sa.Column("updated_at", sa.TIMESTAMP(), nullable=True),
        sa.Column("deleted_at", sa.TIMESTAMP(), nullable=True),
        sa.Column("lang", sa.String(length=255), nullable=True),
        sa.Column("value", sa.Text(), nullable=True),
        sa.Column("nvd_json_id", mysql.INTEGER(display_width=10), nullable=True),
        sa.ForeignKeyConstraint(
            ["nvd_json_id"],
            ["cve.nvd_jsons.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="cve",
    )
    op.create_index(
        "idx_descriptions_deleted_at",
        "descriptions",
        ["deleted_at"],
        unique=False,
        schema="cve",
    )
    op.create_index(
        "idx_descriptions_nvd_json_id",
        "descriptions",
        ["nvd_json_id"],
        unique=False,
        schema="cve",
    )
    op.create_table(
        "references",
        sa.Column("id", mysql.INTEGER(display_width=10), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(), nullable=True),
        sa.Column("updated_at", sa.TIMESTAMP(), nullable=True),
        sa.Column("deleted_at", sa.TIMESTAMP(), nullable=True),
        sa.Column("nvd_xml_id", mysql.INTEGER(display_width=10), nullable=True),
        sa.Column("jvn_id", mysql.INTEGER(display_width=10), nullable=True),
        sa.Column("source", sa.String(length=255), nullable=True),
        sa.Column("tags", sa.String(length=255), nullable=True),
        sa.Column("link", sa.Text(), nullable=True),
        sa.Column("nvd_json_id", mysql.INTEGER(display_width=10), nullable=True),
        sa.ForeignKeyConstraint(
            ["nvd_json_id"],
            ["cve.nvd_jsons.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="cve",
    )
    op.create_index(
        "idx_references_deleted_at",
        "references",
        ["deleted_at"],
        unique=False,
        schema="cve",
    )
    op.create_index(
        "idx_references_jvn_id", "references", ["jvn_id"], unique=False, schema="cve"
    )
    op.create_index(
        "idx_references_nvd_json_id",
        "references",
        ["nvd_json_id"],
        unique=False,
        schema="cve",
    )
    op.create_index(
        "idx_references_nvd_xml_id",
        "references",
        ["nvd_xml_id"],
        unique=False,
        schema="cve",
    )
    op.create_table(
        "vulnerability",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("date_created", sa.DateTime(), nullable=True),
        sa.Column("date_modified", sa.DateTime(), nullable=True),
        sa.Column("comment", sa.Text(), nullable=False),
        sa.Column("exploit_exists", sa.Boolean(), nullable=True),
        sa.Column("cve_id", sa.String(length=255), nullable=True),
        sa.Column("creator_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["creator_id"],
            [u"user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("cve_id"),
    )
    op.create_table(
        "vulnerability_git_commits",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("date_created", sa.DateTime(), nullable=True),
        sa.Column("date_modified", sa.DateTime(), nullable=True),
        sa.Column("commit_hash", sa.String(length=255), nullable=False),
        sa.Column("commit_link", sa.String(length=255), nullable=False),
        sa.Column("repo_name", sa.String(length=255), nullable=False),
        sa.Column("repo_owner", sa.String(length=255), nullable=True),
        sa.Column("repo_url", sa.String(length=255), nullable=True),
        sa.Column("vulnerability_details_id", sa.Integer(), nullable=True),
        sa.Column("tree_cache", mysql.LONGTEXT(), nullable=True),
        sa.ForeignKeyConstraint(
            ["vulnerability_details_id"],
            ["vulnerability.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_vulnerability_git_commits_commit_hash"),
        "vulnerability_git_commits",
        ["commit_hash"],
        unique=False,
    )
    op.create_table(
        "vulnerability_resources",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("date_created", sa.DateTime(), nullable=True),
        sa.Column("date_modified", sa.DateTime(), nullable=True),
        sa.Column("link", sa.String(length=255), nullable=False),
        sa.Column("vulnerability_details_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["vulnerability_details_id"],
            ["vulnerability.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "repository_files",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("date_created", sa.DateTime(), nullable=True),
        sa.Column("date_modified", sa.DateTime(), nullable=True),
        sa.Column("file_name", sa.String(length=255), nullable=False),
        sa.Column("file_path", sa.String(length=255), nullable=False),
        sa.Column("file_hash", sa.String(length=255), nullable=False),
        sa.Column("file_patch", sa.Text(), nullable=False),
        sa.Column("commit_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["commit_id"],
            ["vulnerability_git_commits.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "repository_file_comments",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("date_created", sa.DateTime(), nullable=True),
        sa.Column("date_modified", sa.DateTime(), nullable=True),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("archived_at", sa.DateTime(), nullable=True),
        sa.Column("row_from", sa.Integer(), nullable=True),
        sa.Column("row_to", sa.Integer(), nullable=True),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("sort_pos", sa.Integer(), nullable=True),
        sa.Column("repository_file_id", sa.Integer(), nullable=True),
        sa.Column("creator_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["creator_id"],
            [u"user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["repository_file_id"],
            ["repository_files.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "repository_file_markers",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("date_created", sa.DateTime(), nullable=True),
        sa.Column("date_modified", sa.DateTime(), nullable=True),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("archived_at", sa.DateTime(), nullable=True),
        sa.Column("row_from", sa.Integer(), nullable=True),
        sa.Column("row_to", sa.Integer(), nullable=True),
        sa.Column("column_from", sa.Integer(), nullable=True),
        sa.Column("column_to", sa.Integer(), nullable=True),
        sa.Column("marker_class", sa.String(length=100), nullable=False),
        sa.Column("repository_file_id", sa.Integer(), nullable=True),
        sa.Column("creator_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["creator_id"],
            [u"user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["repository_file_id"],
            ["repository_files.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("repository_file_markers")
    op.drop_table("repository_file_comments")
    op.drop_table("repository_files")
    op.drop_table("vulnerability_resources")
    op.drop_index(
        op.f("ix_vulnerability_git_commits_commit_hash"),
        table_name="vulnerability_git_commits",
    )
    op.drop_table("vulnerability_git_commits")
    op.drop_table("vulnerability")
    op.drop_index("idx_references_nvd_xml_id", table_name="references", schema="cve")
    op.drop_index("idx_references_nvd_json_id", table_name="references", schema="cve")
    op.drop_index("idx_references_jvn_id", table_name="references", schema="cve")
    op.drop_index("idx_references_deleted_at", table_name="references", schema="cve")
    op.drop_table("references", schema="cve")
    op.drop_index(
        "idx_descriptions_nvd_json_id", table_name="descriptions", schema="cve"
    )
    op.drop_index(
        "idx_descriptions_deleted_at", table_name="descriptions", schema="cve"
    )
    op.drop_table("descriptions", schema="cve")
    op.drop_index("idx_cwes_nvd_xml_id", table_name="cwes", schema="cve")
    op.drop_index("idx_cwes_nvd_json_id", table_name="cwes", schema="cve")
    op.drop_index("idx_cwes_jvn_id", table_name="cwes", schema="cve")
    op.drop_index("idx_cwes_deleted_at", table_name="cwes", schema="cve")
    op.drop_table("cwes", schema="cve")
    op.drop_index("idx_cvss3_nvd_json_id", table_name="cvss3", schema="cve")
    op.drop_index("idx_cvss3_jvn_id", table_name="cvss3", schema="cve")
    op.drop_index("idx_cvss3_deleted_at", table_name="cvss3", schema="cve")
    op.drop_table("cvss3", schema="cve")
    op.drop_index("idx_cpes_vendor", table_name="cpes", schema="cve")
    op.drop_index("idx_cpes_uri", table_name="cpes", schema="cve")
    op.drop_index("idx_cpes_product", table_name="cpes", schema="cve")
    op.drop_index("idx_cpes_part", table_name="cpes", schema="cve")
    op.drop_index("idx_cpes_nvd_xml_id", table_name="cpes", schema="cve")
    op.drop_index("idx_cpes_nvd_json_id", table_name="cpes", schema="cve")
    op.drop_index("idx_cpes_jvn_id", table_name="cpes", schema="cve")
    op.drop_index("idx_cpes_formatted_string", table_name="cpes", schema="cve")
    op.drop_index("idx_cpes_deleted_at", table_name="cpes", schema="cve")
    op.drop_table("cpes", schema="cve")
    op.drop_table("user")
    op.drop_index(op.f("ix_cwe_cwe_data_cwe_id"), table_name="cwe_data", schema="cwe")
    op.drop_table("cwe_data", schema="cwe")
    op.drop_index("idx_nvd_xmls_deleted_at", table_name="nvd_xmls", schema="cve")
    op.drop_index("idx_nvd_xmls_cveid", table_name="nvd_xmls", schema="cve")
    op.drop_index("idx_nvd_xmls_cve_detail_id", table_name="nvd_xmls", schema="cve")
    op.drop_table("nvd_xmls", schema="cve")
    op.drop_index("idx_nvd_jsons_deleted_at", table_name="nvd_jsons", schema="cve")
    op.drop_index("idx_nvd_jsons_cveid", table_name="nvd_jsons", schema="cve")
    op.drop_index("idx_nvd_jsons_cve_detail_id", table_name="nvd_jsons", schema="cve")
    op.drop_table("nvd_jsons", schema="cve")
    op.drop_index("idx_jvns_deleted_at", table_name="jvns", schema="cve")
    op.drop_index("idx_jvns_cveid", table_name="jvns", schema="cve")
    op.drop_index("idx_jvns_cve_detail_id", table_name="jvns", schema="cve")
    op.drop_table("jvns", schema="cve")
    op.drop_index("idx_feed_meta_deleted_at", table_name="feed_meta", schema="cve")
    op.drop_table("feed_meta", schema="cve")
    op.drop_index("idx_envcpes_uri", table_name="env_cpes", schema="cve")
    op.drop_index("idx_envcpes_formatted_string", table_name="env_cpes", schema="cve")
    op.drop_index("idx_envcpes_cpe_id", table_name="env_cpes", schema="cve")
    op.drop_index("idx_env_cpes_deleted_at", table_name="env_cpes", schema="cve")
    op.drop_table("env_cpes", schema="cve")
    op.drop_index(
        "idx_cvsss2_extra_nvd_json_id", table_name="cvss2_extras", schema="cve"
    )
    op.drop_index(
        "idx_cvss2_extras_deleted_at", table_name="cvss2_extras", schema="cve"
    )
    op.drop_table("cvss2_extras", schema="cve")
    op.drop_index("idx_cvsss2_nvd_xml_id", table_name="cvss2", schema="cve")
    op.drop_index("idx_cvss2_jvn_id", table_name="cvss2", schema="cve")
    op.drop_index("idx_cvss2_deleted_at", table_name="cvss2", schema="cve")
    op.drop_table("cvss2", schema="cve")
    op.drop_index("idx_cve_details_deleted_at", table_name="cve_details", schema="cve")
    op.drop_index("idx_cve_detail_cveid", table_name="cve_details", schema="cve")
    op.drop_table("cve_details", schema="cve")
    op.drop_index("idx_affects_nvd_json_id", table_name="affects", schema="cve")
    op.drop_index("idx_affects_deleted_at", table_name="affects", schema="cve")
    op.drop_table("affects", schema="cve")
    # ### end Alembic commands ###
