"""Removes redundant index from oss_products.

Revision ID: 8696079cdbfc
Revises: 5dd1d09f15fe
Create Date: 2019-07-27 18:36:47.280273

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "8696079cdbfc"
down_revision = "5dd1d09f15fe"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("vendor", table_name="oss_products")
    op.create_index(
        "idx_cpe_vendor_product",
        "cpes",
        ["vendor", "product"],
        unique=False,
        schema="cve",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index("vendor", "oss_products", ["vendor", "product"], unique=True)
    op.drop_index("idx_cpe_vendor_product", table_name="cpes", schema="cve")
    # ### end Alembic commands ###
