"""Updating the index over CPE to cover nvd_json_id to speed up product lookups using index-only scans.

Revision ID: 9a935d8fb960
Revises: 8696079cdbfc
Create Date: 2019-08-01 11:48:42.277952

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "9a935d8fb960"
down_revision = "8696079cdbfc"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "idx_cpe_product_lookup",
        "cpes",
        ["vendor", "product", "nvd_json_id"],
        unique=False,
        schema="cve",
    )
    op.drop_index("idx_cpe_vendor_product", table_name="cpes", schema="cve")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "idx_cpe_vendor_product",
        "cpes",
        ["vendor", "product"],
        unique=False,
        schema="cve",
    )
    op.drop_index("idx_cpe_product_lookup", table_name="cpes", schema="cve")
    # ### end Alembic commands ###
