"""user login types

Revision ID: 9d370f33f1a0
Revises: 6a577b4c41fe
Create Date: 2020-11-30 12:58:31.046646

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "9d370f33f1a0"
down_revision = "6a577b4c41fe"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user",
        sa.Column(
            "login_type",
            sa.Enum("LOCAL", "GOOGLE", "GITHUB", name="logintype"),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "login_type")
    # ### end Alembic commands ###
