"""products

Revision ID: c77061c72a59
Revises: 4c879a183a73
Create Date: 2020-10-30 17:03:42.379504

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "c77061c72a59"
down_revision = "4c879a183a73"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "product",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("date_created", sa.DateTime(), nullable=True),
        sa.Column("date_modified", sa.DateTime(), nullable=True),
        sa.Column("vendor", sa.String(length=255), nullable=False),
        sa.Column("product", sa.String(length=255), nullable=False),
        sa.Column("is_open_source", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_product_main", "product", ["vendor", "product"], unique=True)
    op.create_table(
        "vulnerable_products",
        sa.Column("vuln_id", sa.Integer(), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["product.id"],
        ),
        sa.ForeignKeyConstraint(
            ["vuln_id"],
            ["vulnerability.id"],
        ),
        sa.PrimaryKeyConstraint("vuln_id", "product_id"),
    )
    op.drop_index("idx_oss_products_main", table_name="oss_products")
    op.drop_table("oss_products")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "oss_products",
        sa.Column("id", mysql.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("date_created", mysql.DATETIME(), nullable=True),
        sa.Column("date_modified", mysql.DATETIME(), nullable=True),
        sa.Column("vendor", mysql.VARCHAR(length=255), nullable=False),
        sa.Column("product", mysql.VARCHAR(length=255), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        mysql_default_charset="utf8",
        mysql_engine="InnoDB",
    )
    op.create_index(
        "idx_oss_products_main", "oss_products", ["vendor", "product"], unique=True
    )
    op.drop_table("vulnerable_products")
    op.drop_index("idx_product_main", table_name="product")
    op.drop_table("product")
    # ### end Alembic commands ###
